"""
Solution generated by ChatGPT
"""
# Parse the input text and store it in a list of lists
calories = []
elf_calories = []
with open('input_data.txt') as f:
  for line in f:
    # If the line is empty, this indicates that we've reached the end of the
    # inventory of the previous Elf, so we add the Elf's inventory to the list
    # of all Elves' inventories, and reset the current Elf's inventory.
    if line.strip() == '':
      calories.append(elf_calories)
      elf_calories = []
    else:
      elf_calories.append(int(line.strip()))

# Add the final Elf's inventory to the list of all Elves' inventories
calories.append(elf_calories)

# Find the sublist with the largest sum of Calories
max_calories = max([sum(c) for c in calories])
max_calories_elf = 333 #calories.index(max_calories)

# Print the results
print(f'Elf {max_calories_elf+1} is carrying the most Calories: {max_calories}')
